### PR TITLE
Mushe

### PR DESCRIPTION
**Pull request by MusheAbdulHakim**
Filemananger for users to manager their files.

### CODE REVIEW

**Comment by nasirkhan** [comment]
@MusheAbdulHakim , 
Thank you for submitting the pull request. 

Here you added the [unisharp/laravel-filemanager](https://github.com/unisharp/laravel-filemanager) package and related files. It is a great package and I used it before, But i moved from there as it was not updating/ fixing the issues regularly.

[alexusmai/laravel-file-manager](https://github.com/alexusmai/laravel-file-manager) package is installed here and integrated with the Posts. You may use this with other parts as well. 

Now, if you please let me the advantages of your suggested package with the current one, then we may replace the existing.

**Comment by MusheAbdulHakim** [comment]
Okay thanks for the feedback.

**Comment by MusheAbdulHakim** [comment]
I have tried [https://github.com/alexusmai/laravel-file-manager](https://github.com/alexusmai/laravel-file-manager) and i still think [https://github.com/unisharp/laravel-filemanager](https://github.com/unisharp/laravel-filemanager) is much better to it.It is very simple to use,it has nice user interface.and ultimately , you don't have struggles with styling after integration.

**Comment by MusheAbdulHakim** [comment]
I will like to contribute to the project.So if there is anything i can do to help let me know.

**Comment by nasirkhan** [comment]
Thank you for your interest in contributing to this project.
Please check the issue where I added a number of tasks/ features. Let's
have a conversation other there.
https://github.com/nasirkhan/laravel-starter/issues/269


--
*Nasir Khan Saikat*
www.nasirkhn.com

**Comment by nasirkhan** [comment]
Hi @MusheAbdulHakim,

I was trying to merge this pull request today and found one issue on the `admin/filemanager` page. From the page source i found that the google analytics code has been added twice on the page and that throwing an error in the console. Can you please look into that?

**Comment by MusheAbdulHakim** [comment]
ok i will look into that

**Comment by MusheAbdulHakim** [comment]
@nasirkhan I have checked and i haven't seen anything like what you have described.
But i can close this pull request and send a new one for you to verify.

**Pull request closed without merging**
